name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to ghcr.io
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
       
    - name: Build and Publish the Docker Image
      uses: docker/build-push-action@v3.0.0
      with:
        file: Docker/Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/helm-repo:latest
        push: true

    